### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by makkaroni8** [NoRiskClient/noriskclient-launcher#45]
![image](https://github.com/NoRiskClient/noriskclient-launcher/assets/39804593/9b655411-6349-4a1f-86b1-32ecfe741ead)

**Comment by SirKnubble** [comment]
1. Launcher is in Closed-Beta, as long as you are not whitelisted, you will get error 403.
2. Issues pls in [NoRiskClient/issues](https://github.com/NoRiskClient/issues)

**Comment by SirKnubble** [comment]
1. Launcher is in Closed-Beta, as long as you are not whitelisted, you will get error 403.
2. Issues pls in [NoRiskClient/issues](https://github.com/NoRiskClient/issues)

> Closed.
