### ISSUE TITLE
Ingame mudul bug

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/noriskclient-launcher#50]
Als ich den xosmetif tab öffnete war nur ein ganz kleines fester da und andere Sachen waren gaenich dar der skin läd die ganze Zeit auch nicht und ich kann auch nur die norisk Client dev Version spielen und es wär cool wenn es auch einen ingame Mod maker gibt wo man mit Blockdraganddrop Code kann wie Scratch oder Minecraft edukation

**Comment by SirKnubble** [comment]
Bugreports in [NoRiekClient/issues](https://github.com/NoRiskClient/issues), am besten mit Screenshot.

**Comment by McCram12** [comment]
Das Problem ist ich kann in nicht reproduzieren es ist einfach paziert man kann es nicht so vorstellen du öffnest die Freudliste jetzt chs da du öfnest die cosmetigs nur ein kleiner Quadrat ausschniet wo man was sehen kann

**Comment by SleepyPxnda** [comment]
Also der Mod Maker wird safe micht kommen. Viel zu viel Aufwand für nichts.
