### ISSUE TITLE
[Linux] "Crash Report" Window

### ISSUE THREAD

**Issue by SpurKomet** [NoRiskClient/noriskclient-launcher#57]
Wenn das Crashreportfenster noch offen ist und das Game erneut crasht, wird nicht mehr der Crashreport (weder der 1. noch der 2.), sondern der Noriskclient in dem Fenster angezeigt.
![Bildschirmfoto_2024-09-02_15-59-15](https://github.com/user-attachments/assets/39022057-feed-4839-bb92-f44f41e015aa)

Linux Mint 21.3 Virginia (xfce)
Norisk Client als deb installiert.

**Comment by SpurKomet** [comment]
https://github.com/user-attachments/assets/22d003ec-2c51-4606-ad20-12129273ac09


Nochmal nen Video vom Problem.

**Comment by SirKnubble** [comment]
Issues in NoRiskClient/issues (und ist bekannt)

**Comment by SpurKomet** [comment]
Ok.

Danke für die Info.
