### ISSUE TITLE
Umlaute buggen herum

### ISSUE THREAD

**Issue by x8laye4r** [NoRiskClient/noriskclient-launcher#63]
Hab voll vergessen dass ich den NoRisk Client gelaunched habe. Bin auf Hypixel gegangen und habe bemerkt, dass die Umlaute nicht funktionieren.
![2024-10-07_16 15 20](https://github.com/user-attachments/assets/e2c5fc92-66f7-46a7-98c8-577fc9cee4d6)

**Comment by SecretBot155** [comment]
ich glaub das hat eher was mit deinem texturepack zu tun kann das sein? probiers mal ohne norisk client aber trotzdem mit tp und schau obs immer noch verbuggt ist, wenn ja keine schuld vom nrc

**Comment by TimLohrer** [comment]
Hier keine issues.. bitte in <https://github.com/NoRiskClient/issues/issues>
