### ISSUE TITLE
Nitro Boost in Cosmetics, ohne Booster

### ISSUE THREAD

**Issue by blacckaxxel** [NoRiskClient/noriskclient-launcher#64]
In den Cosmetics kann man ohne Server Booster sich den Hut "Nitro Boost" abstauben. Ich weiss jetzt nicht ob es daran liegt, dass ich den Client mit Discord verbunden habe oder ob es auch so ohne Probleme geht. Bin jedenfalls kein Booster und konnte es mir einfach geben. 
![Screenshot 2024-10-07 171547](https://github.com/user-attachments/assets/4c7ed0c6-fcb2-4a9f-8a71-75b721622e4e)

**Comment by TimLohrer** [comment]
Hier keine issues.. bitte in <https://github.com/NoRiskClient/issues/issues>

+ Ist fixed :)
