### ISSUE TITLE
Launcher Lädt nicht mehr.

### ISSUE THREAD

**Issue by 2ndSky95** [NoRiskClient/noriskclient-launcher#71]
![Screenshot_1](https://github.com/user-attachments/assets/48936bb3-0717-49b1-8d6a-18fb37ff0c8f)
Der Launcher Lädt nicht mehr nach Neustart des Lounchers. "Nicht in der Whitelist!"

**Comment by 2ndSky95** [comment]
Bin jetzt in der Whitelist und das Problem ist weg.

**Comment by SirKnubble** [comment]
Close.
Und Bugreports in [NoRiskClient/issues](https://github.com/NoRiskClient/issues/issues/new?labels=bug%2Cneeds+validation&projects=github%2F2&template=bug_report.yml&title=%5BBug%5D%3A+)
