### ISSUE TITLE
Kein Icon unter Linux

### ISSUE THREAD

**Issue by Gurkenlor3nz** [NoRiskClient/noriskclient-launcher#72]
Ich benutze den Norisk-Client auf meinem Ubuntu-22.04 PC. Allerdings hat der Norisk-Client kein Icon und ich muss mit der Maus darübergehen, um zu sehen, dass es der NRC ist. Hier ist ein Bild: 
![Bildschirmfoto vom 2024-11-04 18-49-16](https://github.com/user-attachments/assets/878e9cbc-df64-42c2-8329-287037298e3c)

**Comment by SirKnubble** [comment]
Bugreports in [NoRiskClient/issues](https://github.com/NoRiskClient/issues/issues/new?labels=bug%2Cneeds+validation&projects=github%2F2&template=bug_report.yml&title=%5BBug%5D%3A+)
