### ISSUE TITLE
Crash nach Pong

### ISSUE THREAD

**Issue by ReVerrostet** [NoRiskClient/noriskclient-launcher#73]
Fehlermeldung: https://mclo.gs/GCtI2Vz
Ich habe eine Runde Pong gespielt und als diese zu ende war, ist mein spiel gecrasht

**Comment by SirKnubble** [comment]
Bugreports in [NoRiskClient/issues](https://github.com/NoRiskClient/issues/issues/new?labels=bug%2Cneeds+validation&projects=github%2F2&template=bug_report.yml&title=%5BBug%5D%3A+)
