### ISSUE TITLE
McReal 

### ISSUE THREAD

**Issue by Lowkey-Louis** [NoRiskClient/noriskclient-launcher#74]
wenn man ein McReal machen möchte und die mod essentials beutzt kommt dieser fehler und es funktioniert nicht https://prnt.sc/fQS-2GRdcvpt 
Wenn man dann in gespeicherten screenshots geht wird das angezeigt https://prnt.sc/eQLebge_pYke und es wird kein McReal hochgeladen.

**Comment by TimLohrer** [comment]
Bugs bitte in https://github.com/NoRiskClient/issues/issues
